### ISSUE TITLE
P001 error in method definition

### ISSUE THREAD

**Issue by idgserpro** [gforcada/flake8-plone-api#16]
I have a plugin pas with the code:

``` python
def getGroupsForPrincipal(self, principal, request=None):
    """"""
```

Then I get the error:

``` bash
P001 found "getGroupsForPrincipal(" consider replacing it with: plone.api.group.get_groups (since plone.api version 1.0)
```

**Comment by gforcada** [comment]
#9 would be the proper fix, I hope I have time sooner for that...

**Comment by idgserpro** [comment]
It complained of `getGroupsForPrincipal` in my tests. In tests I really need to call this method. There has to be a way of ignore some situations. If I use `noqa`, it can hide other problems.

**Comment by idgserpro** [comment]
Just checked on flake8 documentation:

**you can ignore specific errors on a line with # noqa: <error>, e.g., # noqa: E234**

Is possible for 3.X version.

https://flake8.pycqa.org/en/latest/release-notes/3.0.0.html#b1-2016-06-25

**Comment by idgserpro** [comment]
We couldn't really test the 3.X version, we get the error

https://github.com/plone/plone.recipe.codeanalysis/issues/195

in code-analysis.

**Comment by hvelarde** [comment]
in fact this plugin should not report errors but warnings.

**Comment by gforcada** [comment]
`flake8` is at version 6.0.0 already and the `#noqa: P001` comments are meant to be well supported, I'm closing this, feel free to re-open if you disagree :)
